### ISSUE TITLE
Get function tox_friend_lossless_packet_cb running

### ISSUE THREAD

**Issue by merlink01** [yodakohl/toxpython#3]
Hi Yodakohl,

I'm trying to get the function tox_friend_lossless_packet_cb running.
It seems not to be fully implemented yet.

Do you have an Idea how to fix this.

Thanks for this great Project.

**Comment by merlink01** [comment]
OK, got a second Problem:
friend_send_lossless_packet returns always False.
Any Idea?

**Comment by yodakohl** [comment]
The tox-library interprets the first byte of data in friend_send_lossless_packet as message type. Sending lossless packets are custom packets and are required to have a message type within a certain range (>160). I already started working on this issue as well as the missing callback and hope to finish within 48 hours

**Comment by merlink01** [comment]
You are great, thank you.
